### ISSUE TITLE
HTTP/2 Trailers support

### ISSUE THREAD

**Issue by MouseRider** [petrohi/machine_gun#11]
Hi Peter,

I want to use your library for gRPC calls..
Right now I only need to support Unary calls, so trailers handlers in response only should be enough.
Do you have any plans to add those? Do you need help with that?

Thanks,
Alex

**Comment by petrohi** [comment]
Can you explain (or point to explanation) what trailers are?

**Comment by MouseRider** [comment]
Trailers are optional headers sent at the end of the HTTP/2 request/response.
Response trailers are utilized by gRPC protocol to pass back to client state and optional message(likely for errors only) of the executed request.
You can have a look at my fork (MouseRider/machine_gun) for proposed changes (very minor).

**Comment by petrohi** [comment]
Yes. Looks reasonable. Please create push request.

**Comment by MouseRider** [comment]
Hi Peter,

Found the problem with my original change to support http2 for tcp connections:

Apparently libraries down the call stack do not support list of multiple protocols – just single value.
I guess the right way would be to update all of them.
But for now I had an idea to use conn_opts in request method of machine_gun to supply what protocol I want to use for this request.
This approach uncovered a bug: code does not respect conn_opts supplied as request call parameter.

I have a suggested fix – please have a look in my branch.

Let me know if you want me to create a pull request separately for the fix?

Thank you,
Alex

**Comment by petrohi** [comment]
Yes, two separate pull requests sound good.

**Comment by MouseRider** [comment]
Hi Peter,

Submitted 2 PRs.
Please have a look.

Thank you,
Alex
