### ISSUE TITLE
http2 over tcp

### ISSUE THREAD

**Issue by MouseRider** [petrohi/machine_gun#12]
Hi Peter,

I want to use your library for gRPC calls. We use insecure connections and Gun supports it.
I see that you restrict HTTP/2  to  SSL(TLS) connections only.
Do you have any plans to enable it for insecure connections as well? 
Do you need help with that?

Thanks,
Alex

**Comment by petrohi** [comment]
Yes--having an option for insecure HTTP/2 would be useful. Would love help!
