### ISSUE TITLE
TLS version?

### ISSUE THREAD

**Issue by tombh** [petrohi/machine_gun#17]
I can't seem to find any options here or on Gun about setting the TLS version.

**Comment by petrohi** [comment]
You can pass it in Gun connection options:

```
config :machine_gun,
  default: %{
    conn_opts: %{
      transport_opts: [versions: [:"tlsv1.3"]]
    }
  }
```

`versions` is documented here http://erlang.org/doc/man/ssl.html#type-protocol_versions

**Comment by kdawgwilk** [comment]
This works great for static settings like the use case mentioned above but not for use cases like the following
```elixir
config :machine_gun,
  default: %{
    conn_opts: %{
      tls_opts: [
        verify: :verify_peer,
        cacerts: :certifi.cacerts(),
        depth: 99,
        verify_fun: {&:ssl_verify_hostname.verify_fun/3, [check_hostname: 'amazonaws.com']}
      ]
    }
  }
```
where you need to reference other libraries functions for TLS cert verification.  Any thoughts on how we can pass this to `:machine_gun` and have it make its way to `:gun`
