### ISSUE TITLE
:shutdown

### ISSUE THREAD

**Issue by 9mm** [petrohi/machine_gun#3]
Do you have any idea why I might be getting a lot of `:shutdown` errors? I know theres `:close` when the connection is closed so I'm unsure why I keep getting a lot of these. I asked the owner of `gun` but it wasn't too helpful, he just said whan a process is shutting down thats what happens.

Do you have any idea why Elixir is trying to shut down my processes while there are requests going on?

**Comment by petrohi** [comment]
This might be happening when server is closing connection without the response. Let me check.

**Comment by 9mm** [comment]
Another awesome response, thanks so much 👌🏼

**Comment by 9mm** [comment]
are you going to publish this on hex by chance?

**Comment by petrohi** [comment]
Yes, I will fix #2 and then will publish

**Comment by 9mm** [comment]
you da man 🙏🏼 I really appreciate your prompt assistance. great library btw, i tried several others that just didnt cut it, yours works perfect

**Comment by petrohi** [comment]
I am glad it is useful! Please try https://hex.pm/packages/machine_gun/0.1.3
