### ISSUE TITLE
Difference between :closed and {:closed, _}

### ISSUE THREAD

**Issue by 9mm** [petrohi/machine_gun#5]
Hey, so far I'm handling all the different errors for fine-grained tuning.

I notice that I have some logs showing up under this:

      {:error, %MachineGun.Error{reason: {:closed, _}}} ->

But I have others showing up as this:

      {:error, %MachineGun.Error{reason: :closed}} ->

I'm not quite sure what the difference is?

Thanks!

**Comment by petrohi** [comment]
Machine gun relays these errors from gun--so I would ask there.

**Comment by 9mm** [comment]
Ok will do

**Comment by 9mm** [comment]
Sorry to bother you lol, can you help me interpret what he's saying? 

https://github.com/ninenines/gun/issues/180
