### ISSUE TITLE
cowboy downgrade?

### ISSUE THREAD

**Issue by 9mm** [petrohi/machine_gun#6]
Sorry for all the questions lately.

I added machine_gun to my phoenix project and it downgraded these, I was wondering if you knew why or how to get the latest version.

Thanks

```
  cowboy 2.6.1 => 2.5.0
  cowlib 2.7.0 => 2.6.0
  ranch 1.7.1 => 1.6.2
```

**Comment by petrohi** [comment]
Gun 1.3 currently depends on Cowlib 2.6, which downgrades others.

You can try adding explicit dependency on Cowlib 2.7 with `override: true`.

**Comment by 9mm** [comment]
thanks !
