### ISSUE TITLE
Stream reset by server

### ISSUE THREAD

**Issue by 9mm** [petrohi/machine_gun#7]
I'm running phoenix/cowboy in another app (behind CloudFlare), and now I'm testing it from a separate elixir app using `machine_gun`.

Here's my production request:

      MachineGun.get(url,
        [{"Accept", "*/*"}, {"User-Agent", "Test/1.0"}],
        %{request_timeout: 3000, pool_group: :feeds})

But this will return: 

```
{:error,
 %MachineGun.Error{
   reason: {:stream_error, :protocol_error, :"Stream reset by server."}
 }}
```

The only thing I can think of is that it's somehow related to `http/2`?

When I remove all the arguments in the list like this... it works fine:

      MachineGun.get(url,
        [],
        %{request_timeout: 3000, pool_group: :feeds})

This is my config:

```
config :machine_gun, feeds: %{
  pool_size: 128,         # Poolboy size [1]
  pool_max_overflow: 128, # Poolboy max_overflow [1]
  pool_timeout: 60_000,
  conn_opts: %{}          # Gun connection options [2]
}
```
I've tried sending a request to https://httpbin.org to see if some kind of default header was getting added that was causing phoenix to throw up, yet the 2 requests are identical except for those 2 headers that get removed... so I'm not sure what else it could be?

**Comment by petrohi** [comment]
Please try lowercasing header names. Many HTTP/2 implementations reject non-lowercase headers.

**Comment by 9mm** [comment]
wow awesome that fixed it, thanks!
